---
---

<div id="Published Articles" class="section level3">
<h3>Published Articles:</h3>


* <strong>Almutiry, W.</strong>, & Deardon, R. (2020). "Incorporating contact network uncertainty in individual level models of infectious disease using approximate Bayesian computation". <em>The international journal of biostatistics</em>, 16(1).
<a href="https://doi.org/10.1515/ijb-2017-0092" class="uri">https://doi.org/10.1515/ijb-2017-0092</a>.

* <strong>Almutiry, W.</strong>, KV, V. W., & Deardon, R. (2021). "Continuous Time Individual-Level Models of Infectious Disease: Package EpiILMCT". <em>Journal of Statistical Software</em>, 98, 1-44.
<a href="https://www.jstatsoft.org/article/view/v098i10" class="uri">https://www.jstatsoft.org/article/view/v098i10</a>.

* <strong>Almutiry, W.</strong>, & Deardon, R. (2021). "Contact network uncertainty in individual level models of infectious disease transmission". <em>Statistical Communications in Infectious Diseases</em>, 13(1).

* Otmani, S., Boulaaras, S., & <strong>Almutiry, W.</strong> (2020). "The maximum norm analysis of a nonmatching grids method for a class of parabolic biharmonic equation with mixed boundary condition". <em>Journal of Intelligent & Fuzzy Systems</em>, 38(3), 2551-2560.
<a href="https://content.iospress.com/articles/journal-of-intelligent-and-fuzzy-systems/ifs179542" class="uri">https://content.iospress.com/articles/journal-of-intelligent-and-fuzzy-systems/ifs179542</a>.

* KV, V. W., <strong>Almutiry, W.</strong>, & Deardon, R. (2020). "Individual-Level Modelling of Infectious Disease Data: EpiILM". <em>R Journal</em>, 12(1).
<a href="https://doi.org/10.32614/RJ-2020-020" class="uri">https://doi.org/10.32614/RJ-2020-020</a>.

* Alshammari, S. M., <strong>Almutiry, W.</strong>, Gwalani, H., Algarni, S. M., & Saeedi, K. (2021). "Measuring the impact of suspending Umrah, a global mass gathering in Saudi Arabia on the COVID-19 pandemic". <em>Computational and Mathematical Organization Theory</em>, 1-26. <a href="https://doi.org/10.1007/s10588-021-09343-y" class="uri">https://doi.org/10.1007/s10588-021-09343-y</a>.

* Abdullah Ali H. Ahmadini, Amara Javed, Sohail Akhtar, Christophe Chesneau, Farrukh Jamal, Shokrya S. Alshqaq, Mohammed Elgarhy, Sanaa Al-Marzouki, M. H. Tahir, <strong>Waleed Almutiry</strong> (2021). "Robust Assessing the Lifetime Performance of Products with Inverse Gaussian Distribution in Bayesian and Classical Setup". <em>Mathematical Problems in Engineering</em>, vol. 2021, Article ID:4582958, 9 pages. <a href="https://doi.org/10.1155/2021/4582958" class="uri">https://doi.org/10.1155/2021/4582958</a>.

* <strong>Waleed Almutiry</strong> (2021). "Inverted Length-Biased Exponential Model: Statistical Inference and Modeling".  <em>Journal of Mathematics</em>, vol. 2021, Article ID 1980480, 8 pages. <a href="https://doi.org/10.1155/2021/1980480" class="uri">https://doi.org/10.1155/2021/1980480</a>.

* M. Shrahili, I. Elbatal, <strong>Waleed Almutiry</strong>, Mohammed Elgarhy (2021). "Estimation of Sine Inverse Exponential Model under Censored Schemes". <em>Journal of Mathematics</em>, vol. 2021, Article ID 7330385, 9 pages. <a href="https://doi.org/10.1155/2021/7330385" class="uri">https://doi.org/10.1155/2021/7330385</a>.

* Khan S, Balogun OS, Tahir MH, <strong>Almutiry W.</strong>, Alahmadi AA. (2021). "An Alternate Generalized Odd Generalized Exponential Family with Applications to Premium Data". <em>Symmetry</em>. 13(11):2064. <a href="https://doi.org/10.3390/sym13112064" class="uri">https://doi.org/10.3390/sym13112064</a>.

* A.S. Al-Moisheer, I. Elbatal, <strong>Waleed Almutiry</strong>, Mohammed Elgarhy (2021). "Odd Inverse Power Generalized Weibull Generated Family of Distributions: Properties and Applications". <em>Mathematical Problems in Engineering</em>, vol. 2021, Article ID 5082192, 17 pages. <a href="https://doi.org/10.1155/2021/5082192" class="uri">https://doi.org/10.1155/2021/5082192</a>.

* <strong>Waleed Almutiry</strong>, Amani Abdullah Alahmadi, Ibrahim Elbatal, Ibrahim E. Ragab, Oluwafemi Samson Balogun, Mohammed Elgarhy (2021). "Application to Engineering and Medical Data Using Three-Parameter Exponential Model". <em>Mobile Information Systems</em>, vol. 2021, Article ID 9550156, 14 pages. <a href="https://doi.org/10.1155/2021/9550156" class="uri">https://doi.org/10.1155/2021/9550156</a>.

* Bantan, R.A.R.; Chesneau, C.; Jamal, F.; Elgarhy, M.; <strong>Almutiry, W.</strong>; Alahmadi, A.A. (2021). "Study of a Modified Kumaraswamy Distribution". <em>Mathematics</em>, 2021, 9, 2836. <a href="https://doi.org/10.3390/math9212836" class="uri">https://doi.org/10.3390/math9212836</a>.

* Abouagwa, M.; Bantan, R.A.R.; <strong>Almutiry, W.</strong>; Khalaf, A.D.; Elgarhy, M. (2021). "Mixed Caputo Fractional Neutral Stochastic Differential Equations with Impulses and Variable Delay". <em>Fractal Fract</em>, 5, 239. <a href="https://doi.org/10.3390/fractalfract5040239" class="uri">https://doi.org/10.3390/fractalfract5040239</a>.

</div>



<div id="Accepted Articles" class="section level3">
<h3>Accepted Articles:</h3>

* Abdenour Hamdaoui, <strong>Waleed Almutiry</strong>, Abdelkader Benkhaled, Mekki Terbeche (2021). "A study of minimax shrinkage estimators and estimators dominating the James-Stein estimator under the balanced loss function". Sumbitted to <em>Open Mathematics</em>.

</div>


<div id="Theses" class="section level3">
<h3>Theses:</h3>

* <strong>Almutiry, W.</strong> (2018) "[Incorporating Contact Network Uncertainty in Individual Level Models of Infectious Disease within a Bayesian Framework](https://atrium.lib.uoguelph.ca/xmlui/bitstream/handle/10214/14120/Almutiry_Waleed_201808-PhD.pdf?sequence=5&isAllowed=y)" Ph.D. Thesis, Department of Mathematics and Statistics, University of Guelph, Canada. 
* <strong>Almutiry, W.</strong> (2018) "Modelling the nasal carriage of Staphylococcus aurues in
mothers and their infants over time" M.Sc. Thesis, Department of Mathematics and Statistics, Lancaster University, UK.

</div>